server:
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        password: d34360807e4e1bbd8fcae7ac405598613d38dadf7dd331e4710c3e6bb590e476
        username: neqvfnmtifgzvf
        url: jdbc:postgresql://${DB_HOST}:5432/datthkt5u8stm?user=neqvfnmtifgzvf&password=d34360807e4e1bbd8fcae7ac405598613d38dadf7dd331e4710c3e6bb590e476
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                format_sql: true
        show-sql: true
        generate-ddl: true

