server:
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        password: 43a31910fdf552dd729763532f66b4c1d8d317efd0b7f10c11bc175bb496337f
        username: xuyzpgwpvufbpb
        url: jdbc:postgresql://${DB_HOST}:5432/d902ihl517e033?user=xuyzpgwpvufbpb&password=43a31910fdf552dd729763532f66b4c1d8d317efd0b7f10c11bc175bb496337f
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                format_sql: true
        show-sql: true
        generate-ddl: true

